//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioTecnico3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipos_incidencias
    {
        public int id_tipo_incidencia { get; set; }
        public string nombre_tipo_incidencia { get; set; }
    }
}
