//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioTecnico3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id_usuario { get; set; }
        public int id_tipo_usuario { get; set; }
        public int id_privilegio { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string dpi { get; set; }
        public int id_direccion { get; set; }
        public string telefono { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public bool acceso { get; set; }
        public string email { get; set; }
        public byte[] fotografia { get; set; }
        public byte[] firma { get; set; }
    }
}
